# This contain sample config Roll Back execution tasks
# - name: REVIEW BGP SUMMARY
#   sros_command:
#     commands:
#       - show vswitch-controller xmpp-server
#     wait_for: result[0] contains Functional
#     # provider: "{{ cli }}"
#   register: temp_var
# - debug: msg="{{ temp_var.stdout_lines }}"

# - name: Run show version and check to see if output contains sros
#   community.network.sros_command:
#     commands: show version
#     wait_for: result[0] contains sros
#     provider: "{{ cli }}"

# - name: Run multiple commands on remote nodes
#   community.network.sros_command:
#     commands:
#       - show version
#       - show port detail
#     provider: "{{ cli }}"

# - name: Run multiple commands and evaluate the output
#   community.network.sros_command:
#     commands:
#       - show version
#       - show port detail
#     wait_for:
#       - result[0] contains TiMOS-B-14.0.R4
#     provider: "{{ cli }}"